### ISSUE TITLE
Wrong directory permissions

### ISSUE THREAD

**Issue by langouste** [robertdebock/ansible-role-git#1]
## Describe the bug
`0644` mode is apply to the home directory when the task `create directory for git configuration` is executed. This cause permission denied error on the user shell.

## Playbook

```yaml
---
#file: playbook.yml

- name: Converge
  hosts: all
  gather_facts: yes
  
  vars:
    users_group_list:
      - name: langouste
    users_user_list:
      - name: langouste
        group: langouste
    git_username: langouste
    git_groupname: langouste
    git_repository_destination: /home/langouste/github.com/langouste

  roles:
    - role: robertdebock.users
    - role: robertdebock.git
```

```yaml
---
#file: requirements.yml

- robertdebock.users
- robertdebock.git
```

## Output

On the managed node :
```bash
$ su - langouste
su: warning: cannot change directory to /home/langouste: Permission denied
-bash: /home/langouste/.bash_profile: Permission denied
```

## Environment

- Control node OS: Ubuntu 19.10
- Control node Ansible version: 2.8.3
- Managed node OS: docker with systemd - [Ubuntu Focal](https://hub.docker.com/r/robertdebock/ubuntu)

## Steps to reproduce

```bash
$ docker run --name ubuntu-systemd --tty --privileged --volume /sys/fs/cgroup:/sys/fs/cgroup:ro robertdebock/ubuntu:latest
```
```bash
$ ansible-playbook -c docker -i ubuntu-systemd, playbook.yml
```
```bash
$ docker exec -it ubuntu-systemd bash -c 'su - langouste'
```
