### ISSUE TITLE
Template error while templating string: no test named 'boolean'

### ISSUE THREAD

**Issue by Tomasito665** [robertdebock/ansible-role-git#3]
## Describe the bug
Hi there! I am trying to run the playook, but the "test if git_force is set correctly" assert fails. It fails both when explicitly defining `git_force` and when leaving it empty.

## Playbook

```yaml
---
- hosts: localhost
  vars:
    git_username: "{{ ansible_env.USER }}"
    git_groupname: "{{ ansible_env.USER }}"
    git_repository_destination: "{{ ansible_env.HOME }}/Development"
    git_force: no
    git_repositories:
      - repo: https://github.com/robertdebock/ansible-role-git
  roles:
    - { role: robertdebock.git }
```

## Output

```
PLAY [localhost] *************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
ok: [localhost]

TASK [robertdebock.git : include assert.yml] *********************************************************************************************************
included: /home/jortola/.ansible/roles/robertdebock.git/tasks/assert.yml for localhost

TASK [robertdebock.git : test if git_repository_destination is set correctly] ************************************************************************
ok: [localhost]

TASK [robertdebock.git : test if git_force is set correctly] *****************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'git_force is boolean' failed. The error was: template error while templating string: no test named 'boolean'. String: {% if git_force is boolean %} True {% else %} False {% endif %}"}

PLAY RECAP *******************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

## Environment

- Control node OS: Ubuntu 20.04.1 LTS
- Control node Ansible version: 2.9.6
- Managed node OS: Ubuntu 20.04.1 LTS (same machine, running ansible against localhost)
